#!/bin/bash
ACTION=${1?Usage: $0 open|close}
if [ "$ACTION" = "open" ]; then
  sudo ufw allow proto tcp from 192.168.0.0/16 to any port 8080
elif [ "$ACTION" = "close" ]; then
  sudo ufw delete allow proto tcp from 192.168.0.0/16 to any port 8080
fi
